### DISCUSSION TITLE
How to attach a built HUGO page to the release

### DISCUSSION THREAD

**Discussion by Plaenkler** [StephaneBour/actions-calver#8] [Q&A]
Hi,

today it occurred to me how great it would be to attach a built version of the web pages to each `calver` release. Currently we use the following workflow for each release:

```
[...]
steps:
  - uses: actions/checkout@v3

  - name: Calver Release
    uses: StephaneBour/actions-calver@master
    id: calver
    with:
      pre: false
      release: true
      date_format: "%Y.%V"
      release_branch: main
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Also, we can easily build the page in one action and store the result in a branch `x` :

```
[...]
- name: Setup Hugo
  uses: peaceiris/actions-hugo@v2
  with:
    hugo-version: 'latest'
    extended: true

- name: Build
  run: hugo -s ./Site/ --minify
[...]
```

Now the central question: **How can I attach an archive (.zip) of this branch to the release when pushing to main**?
