### ISSUE TITLE
Latest updates cause errors

### ISSUE THREAD

**Issue by Plaenkler** [StephaneBour/actions-calver#20]
Since the last updates, all workflows with this action fail. I don't understand the problem straight away.

```text
Unable to process file command 'output' successfully.
Invalid format '* Merge pull request #29 from LaKiS-GbR/dependencies ([50394ec](https://github.com/LaKiS-GbR/***/commit/***)), closes [#29](https://github.com/LaKiS-GbR/***/issues/29)'
```

```yaml
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Calver Release
        uses: StephaneBour/actions-calver@master
        id: calver
        with:
          pre: false
          release: true
          date_format: "%Y.%V"
          release_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by pedrograu** [comment]
I am facing the same error also from the last updates, here is my configuration

```
name: Specify release version
        uses: StephaneBour/actions-calver@master
        id: calver
        with:
          date_format: "%Y-%m-%d-%H%M"
          release: true
          release_branch: main
     env:
          GITHUB_TOKEN: ${{ secrets.CALVER }}     
```
