### ISSUE TITLE
[bug] subsequent runs fail validation

### ISSUE THREAD

**Issue by NickLarsenNZ** [StephaneBour/actions-calver#4]
I have configured my workflow like so:

```yml
    - name: Calver Release
      uses: StephaneBour/actions-calver@master
      id: calver
      with:
        date_format: "stage-%Y-%m-%d"
        release: ${{ github.event_name == 'push' && github.ref == 'refs/heads/stage' }} # disable, or update to stage?
        release_branch: stage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

- When I do an initial run, I get a tag `stage-2021-12-16`.
- I run again (even if there is no new commit) and get tag `stage-2021-12-16.1`.
- On another run (in this case via a new commit), the workflow incorrectly completes successfully, and an error is shown:
   ```
   Last hash : d5ce81bd712de5c65c05d029e194b75d8d2ba8d4
   Last release : stage-2021-12-16
   Last major release : stage-2021-12-16
   Minor release
   Next release : stage-2021-12-16.1
   ##  (2021-12-16)

   * noop ([e8067be](https://github.com/me/playground/commit/e8067be))
   * remove %V (posix week) ([d5ce81b](https://github.com/me/playground/commit/d5ce81b))
   Create release : true
   { "tag_name": "stage-2021-12-16.1", "target_commitish": "stage", "name": "stage-2021-12-16.1", "body": "## (2021-12-16)\n\n* noop ([e8067be](https://github.com/me/playground/commit/e8067be))\n* remove %V (posix week) ([d5ce81b](https://github.com/me/playground/commit/d5ce81b))", "draft": false, "prerelease": false }
   {
     "message": "Validation Failed",
     "errors": [
       {
         "resource": "Release",
         "code": "already_exists",
         "field": "tag_name"
       }
     ],
     "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-release"
   }
   ```

_FYI, `noop` was the commit message_
